import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts';
import './globals.css';
import Header from '@/app/components/header/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header/>
        <main className="p-6">
          {children}
        </main>
        </body>
    </html>
  );
}
